title: Your awesome title
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "/gh-pages-test"
url: "https://thenjip.github.com"
github_username: thenjip

remote_theme: "lorepirri/cayman-blog"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_page_refs: ['about', 'contact']

exclude:
  - "Gemfile*"
  - "README.md"
