name: Deploy the site on GitHub Pages
on:
  push:
    branches:
      - master


jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 'Deploy'
        uses: 'peaceiris/actions-gh-pages@v3'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './jekyll'
          enable_jekyll: true
